name: "Hello World Dart Action"
description: "A template to demonstrate how to build a Dart action. Greet someone and record the time."
branding:
  color: blue
  icon: feather
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
    value: ${{ steps.main-step.outputs.time }}
runs:
  # See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
  using: "composite"
  steps:
    - id: main-step
      env:
        INPUT_WHO-TO-GREET: ${{ inputs.who-to-greet }}
      run: |
        cd $GITHUB_ACTION_PATH/app
        pub get
        dart bin/main.dart
      shell: bash
