name: app
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  github_actions_toolkit:
    git:
      url: https://github.com/axel-op/github_actions_toolkit.dart

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
