name: Example workflow

on: push

jobs:
  example:
    runs-on: ubuntu-latest

    container: google/dart:2

    steps:
      - uses: axel-op/hello-world-dart-action@composite
        id: dart-action
        with:
          who-to-greet: "you"
      - run: echo 'The time was ${{ steps.dart-action.outputs.time }}'
